# Generated by Django 4.1.2 on 2022-10-05 13:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glassari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='posts_img/')),
                ('body', models.TextField()),
                ('post_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('scince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_darslik.scince')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='resource_img/')),
                ('file', models.FileField(upload_to='resource_file/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_darslik.resourcecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PractisTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practis_name', models.CharField(max_length=255)),
                ('practis_slug', models.SlugField(max_length=255)),
                ('scince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_darslik.scince')),
            ],
        ),
        migrations.CreateModel(
            name='Practis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.TextField()),
                ('solusion', models.TextField(blank=True, null=True)),
                ('checking', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('practis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_darslik.practistheme')),
            ],
        ),
    ]
