# Generated by Django 4.1.2 on 2022-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_darslik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('ball', models.IntegerField()),
                ('timer', models.IntegerField(blank=True, default=20, null=True)),
            ],
        ),
    ]
