# Generated by Django 4.1.2 on 2022-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_darslik', '0004_alter_resource_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
