# Generated by Django 4.1.2 on 2022-10-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_darslik', '0006_alter_resource_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glassari',
            new_name='Glossary',
        ),
    ]
