# Generated by Django 4.1.2 on 2022-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_darslik', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='practistheme',
            name='practis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
